#!/usr/bin/env bash
# Assembles the static tree for autokorrektur.org into OUT (default site/dist, gitignored):
#   /              site/index.html (de), en.html, impressum.html, site.css, robots.txt, icons/, img/
#   /privacy       privacy.html rendered by pandoc from PRIVACY_POLICY.md (German, the URL the Play
#                  listing points at) -- so the hosted policy cannot drift from the file
#   /privacy-en    privacy-en.html from PRIVACY_POLICY.en.md (minus its italic maintainers' note)
#   /download/     the signed `core` release APK (arm64-v8a) named with the versionName, plus
#                  SHA256SUMS -- the sideload route while the Play listing is not live
# Then precompresses text files (brotli, zstd, gzip) for Caddy's `precompressed`.
# Same shape as Laberampel's site/build.sh, without the browser app. Needs: pandoc, zstd, git.
# Deploying is site/deploy.sh. Nothing here touches the network.
#
# The APK is whatever `./gradlew :app:assembleCoreRelease` last produced, vetted and named by
# scripts/stage_release_apk.sh -- the script the GitHub release of a tag goes through as well, so
# autokorrektur.org and GitHub serve byte-identical files. It must carry this version, contain
# arm64 code and be signed with the release key, or the build stops.
#
# DOWNLOAD_VERSION overrides the version the pages *claim* to serve, for a pages-only change (an
# Impressum fix) that must not force a rebuild the source has moved past; pair it with deploy.sh
# KEEP_DOWNLOAD=1 so /download/ on the server is left alone, and with APK_BUILD_DATE if the local
# APK is not the published one. Never republish different bytes under a name people have
# checksummed: R8 output is not reproducible.
set -euo pipefail
repo="$(cd "$(dirname "$0")/.." && pwd)"
# The absolute URLs the Open Graph tags need (a scraper resolves no relative path).
# site.env is the one place in this repo that names the domain -- never hardcode it here.
. "$repo/site/site.env"
base_url="https://${SITE_DOMAIN:?set SITE_DOMAIN in site/site.env}"
out="${1:-$repo/site/dist}"
case "$out" in /*) ;; *) out="$PWD/$out" ;; esac

for tool in pandoc zstd brotli git; do
  command -v "$tool" >/dev/null || { echo "build.sh: $tool not installed" >&2; exit 1; }
done
# versionName the way app/build.gradle.kts computes it: git describe against the v* tags only, so
# an assets-vN tag on main cannot name a build.
source_version=$(git -C "$repo" describe --tags --match 'v[0-9]*' --always 2>/dev/null || echo unknown)
version="${DOWNLOAD_VERSION:-$source_version}"
# app/build.gradle.kts strips the leading "v" from the tag for the versionName users see; the APK
# filename and the metadata check below use that form, the pages print it too.
apk_version="${version#v}"
built=$(git -C "$repo" log -1 --format=%cd --date=short 2>/dev/null || date -u +%Y-%m-%d)

# --- the APK the download page will serve --------------------------------------------------------
# Staged (and vetted: this version, arm64, release key) before the old output is removed, so a
# refused APK leaves the previous build intact. With DOWNLOAD_VERSION the version check compares
# against the published release instead of against HEAD, so it still bites.
stage=$(mktemp -d); trap 'rm -rf "$stage"' EXIT
apk_path=$("$repo/scripts/stage_release_apk.sh" "$apk_version" "$stage")
apk_name=$(basename "$apk_path")

rm -rf "$out"; mkdir -p "$out/icons" "$out/img" "$out/download"
mv "$stage/$apk_name" "$stage/SHA256SUMS" "$out/download/"
cp -p "$repo"/site/{index.html,en.html,impressum.html,site.css,robots.txt} "$out/"
cp -p "$repo"/site/icons/* "$out/icons/"
cp -p "$repo/media/image_1_with_car_640x640.png" "$out/img/before.png"
cp -p "$repo/media/image_1_without_car_640x640.png" "$out/img/after.png"
# The Open Graph / Twitter card. Deliberately carries no text: one image serves both
# languages, and text baked into a bitmap is the bug class this project has shipped before
# (CLAUDE.md, the exported image that said VORHER on English devices).
cp -p "$repo/media/og-card-1200x630.jpg" "$out/img/og-card.jpg"

# --- /privacy, /privacy-en from the two policy files ---------------------------------------------
# Drops an italic preamble (a paragraph in _..._ right after the title: repo notes, not policy text).
render_policy() { # <source .md> <output .html> <lang> <title> <home href> <nav html> <trailing note html> <slug> <og locale> <description>
  local src=$1 dst=$2 lang=$3 title=$4 home=$5 nav=$6 note=$7 slug=$8 oglocale=$9 desc=${10}
  python3 - "$src" > "$dst.body.md" <<'PY'
import re, sys
text = open(sys.argv[1], encoding="utf-8").read()
# The first paragraph that is entirely _italic_ (within the head of the file) is the repo note.
text = re.sub(r"(?ms)\A(.{0,400}?\n\n)_[^\n]*_\n\n", r"\1", text, count=1)
sys.stdout.write(text)
PY
  {
    cat <<HTML
<!DOCTYPE html>
<html lang="$lang">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$title</title>
<!-- Generated by site/build.sh from $(basename "$src"); edit that file, never this one. -->
<meta name="description" content="$desc">
<link rel="stylesheet" href="site.css">
<link rel="icon" href="icons/icon.svg" type="image/svg+xml">
<link rel="canonical" href="$base_url/$slug">
<meta property="og:type" content="website">
<meta property="og:site_name" content="AutoKorrektur">
<meta property="og:locale" content="$oglocale">
<meta property="og:url" content="$base_url/$slug">
<meta property="og:title" content="$title">
<meta property="og:description" content="$desc">
<meta property="og:image" content="$base_url/img/og-card.jpg">
<meta property="og:image:type" content="image/jpeg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
</head>
<body>
<header class="site">
  <img src="icons/icon.svg" alt="" width="44" height="44">
  <a class="name" href="$home">AutoKorrektur</a>
  <nav>$nav</nav>
</header>
<main class="doc">
HTML
    pandoc -f gfm -t html5 "$dst.body.md"
    cat <<HTML
<p class="note">$note</p>
</main>
<footer class="site">$nav</footer>
</body>
</html>
HTML
  } > "$dst"
  rm "$dst.body.md"
}
render_policy "$repo/PRIVACY_POLICY.md" "$out/privacy.html" de "AutoKorrektur – Datenschutzerklärung" "./" \
  '<a href="./">Startseite</a><a href="impressum">Impressum</a><a href="privacy-en" lang="en" hreflang="en">English</a>' \
  "Gilt für die Android-App. Hosting dieser Website: <a href=\"impressum\">Impressum</a>. Text zum Stand von App-Version $version." \
  privacy de_DE "Was die AutoKorrektur-App speichert und was nicht: alle Bildverarbeitung bleibt auf dem Gerät, es gibt kein Konto und kein Tracking."
render_policy "$repo/PRIVACY_POLICY.en.md" "$out/privacy-en.html" en "AutoKorrektur – Privacy Policy" "en.html" \
  '<a href="en.html">Home</a><a href="impressum">Impressum</a><a href="privacy" lang="de" hreflang="de">Deutsch</a>' \
  "Applies to the Android app; the German <a href=\"privacy\" lang=\"de\">Datenschutzerklärung</a> is the binding text. Hosting of this website: <a href=\"impressum\">Impressum</a> (German). Text as of app version $version." \
  privacy-en en_GB "What the AutoKorrektur app stores and what it does not: all image processing stays on the device, with no account and no tracking."

# --- /download/ (staged above) --------------------------------------------------------------------
apk_mb=$(( ($(stat -c%s "$out/download/$apk_name") + 524288) / 1048576 ))
# The page's "built" date describes the APK that is *published*, which is not always the local
# rebuild: a pages-only deploy (DOWNLOAD_VERSION + deploy.sh KEEP_DOWNLOAD=1) leaves /download/ as
# it is on the server, so the date must be overridable. The staged copy keeps the build's mtime.
apk_date=${APK_BUILD_DATE:-$(date -u -r "$out/download/$apk_name" +%Y-%m-%d)}

# --- placeholders ---------------------------------------------------------------------------------
for page in index.html en.html impressum.html; do
  sed -i -e "s|__APK_FILE__|$apk_name|g" -e "s|__APK_MB__|$apk_mb|g" \
    -e "s|__APK_VERSION__|$apk_version|g" -e "s|__APK_DATE__|$apk_date|g" \
    -e "s|__VERSION__|$version|g" -e "s|__DATE__|$built|g" \
    -e "s|__BASE_URL__|$base_url|g" "$out/$page"
  if grep -q '__[A-Z0-9_]*__' "$out/$page"; then echo "build.sh: unfilled placeholder in $page" >&2; exit 1; fi
done

# --- precompress (Caddy: file_server precompressed br zstd gzip) ---------------------------------
find "$out" -type f \( -name '*.html' -o -name '*.css' -o -name '*.svg' -o -name '*.txt' \) -print0 |
  xargs -0 -r -P "$(nproc)" -I{} sh -c '
    brotli -kf "$1"
    zstd -q -kf -19 "$1"
    gzip -kf -9 "$1"' _ {}

echo "build.sh: $out -- version $version ($built), $(find "$out" -type f | wc -l) files, $(du -sh "$out" | cut -f1)"
echo "build.sh: /download/$apk_name -- $apk_mb MB, built $apk_date, sha256 $(cut -d' ' -f1 "$out/download/SHA256SUMS")"
